### ISSUE TITLE
Properties

### ISSUE THREAD

**Issue by AdamIshay** [izuminka/reasoning_about_actions#24]
Thank you for you interesting work!

I have encountered some parts of the dataset that I don't understand. I have looked at the blocksworld domain, for the following.

(1) In the domain description, persistent is one of the 4 types, but they are not ever mentioned again. Conversely, self constraint properties are not listed initially as one of the 4 types, but are mentioned later. Are these two types supposed to refer to the same type of property? 

(2) I noticed that sometimes there are cases where the questions asks about properties, but it is not clear to me why some are listed while others are not in the ground truth label. For example, in the dataset, in:

"ActionsReasoningBenchmark_data/prompts_for_test/data_for_test/without_random_sub/without_ramifications/few_shot_0/blocksworld/Instance_10.jsonl", 

the 30th item (id: 190b830c-3e08-4879-975d-1b4ec30eb43f) has a query to "list all valid properties of the state".

“hand is not holding anything” is listed in the ground truth label, but “block b3 is not clear” is not listed. According to the domain description, regarding derived properties:
“In this domain, they are: a block is clear, hand is empty, a block is not clear and hand is not empty.” 
Shouldn’t this be included (assuming derived properties are valid properties)? According to my interpretation, there are many missing properties which include negations (block X is not on top of block Y, etc.)

Also, in 
"ActionsReasoningBenchmark_data/prompts_for_test/data_for_test/without_random_sub/without_ramifications/few_shot_0/blocksworld/Instance_3.jsonl"

The 43rd item (id: c19b62a9-a4ca-4913-adaf-579b1245a38b) asks about the number of static properties of the state and in the domain description there are 0 listed, but the ground truth says there are 2. Am I missing something?

Any help is appreciated, thank you!

**Comment by DivijH** [comment]
1) Yes, "Self-Constrained" and "Persistent" properties are the same. In our paper, we also refer to these properties as Self-Constrained instead of Persistent, as we feel it better conveys this property's meaning.

2) When queried about "list all valid properties of the world" we consider only the positive properties. Therefore, properties like "Block b3 is NOT clear" are not included in the ground truth. Note that the property "Hand is not holding anything" is paraphrased for the property "Hand is empty" which is a positive fluent.

Thanks for pointing this out. The response for the static property should be 0. A small bug while calculating the properties affected just 9 questions in the entire dataset. We have re-generated the values for those and updated the dataset.
